.\" Manpage for delatex.
.\" Contact gdetor@protonmail.ch to correct errors or typos.
.TH man 1 "2014" "1.0" "delatex man page"
.SH NAME
delatex \- deletes all the latex-derivative useless files
.SH SYNOPSIS
delatex
.SH DESCRIPTION
delatex is a Python script for deleting all the latex-derivative files in a
folder and in its all subfolders.
.SH OPTIONS
The delatex does not take any options.
.SH AUTHOR
Georgios Detorakis (gdetor@protonmail.ch)
.SH REPORTING BUGS
No known bugs. Report any bug to gdetor@protonmail.ch
.SH COPYRIGHT
Copyright  ©  2014  Georgios Detorakis BSD 3-Clause License 
<http://opensource.org/licenses/BSD-3-Clause>.
This is free software: you are free to change and redistribute it.  
There is  NO  WARRANTY, to the extent permitted by law.
.SH SEE ALSO
