.\" Manpage for wclatex.
.\" Contact gdetor@protonmail.ch to correct errors or typos.
.TH man 1 "2014" "1.0" "wclatex man page"
.SH NAME
wclatex \- counts the non-latex and the latex words in a .tex file.
.SH SYNOPSIS
wclatex [FILE]
.SH DESCRIPTION
wclatex is a Python script that exploits regular expressions in order to 
count the pre-defined latex words and text words in a tex file. 
.SH OPTIONS
The wclatex does not take any options. However, you must provide a file name.
.SH AUTHOR
Georgios Detorakis (gdetor@protonmail.ch)
.SH REPORTING BUGS
No known bugs. Report any bug to gdetor@protonmail.ch
.SH COPYRIGHT
Copyright  ©  2014  Georgios Detorakis BSD 3-Clause License 
<http://opensource.org/licenses/BSD-3-Clause>.
This is free software: you are free to change and redistribute it.  
There is  NO  WARRANTY, to the extent permitted by law.
.SH SEE ALSO
